[tool.poetry]
name = "adventofcode_2023"
version = "0.1.0"
description = ""
authors = ["Till"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
advent-of-code-data = "^2.0.1"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
